version: '3'

services:
  surround_occ:
    image: surround_occ
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - type: bind
        source: $HOME
        target: "/config"