version: '3'

services:
  surround_occ:
    image: surround_occ
    tty: true
    stdin_open: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - type: bind
        source: $NUSCENES_DIR/v1.0-mini
        target: /SurroundOcc/data/nuscenes
      - type: bind
        source: $NUSCENES_DIR/v1.0-test_meta/v1.0-test
        target: /SurroundOcc/data/nuscenes/v1.0-test
      - type: bind
        source: $NUSCENES_DIR/v1.0-trainval_meta/v1.0-trainval
        target: /SurroundOcc/data/nuscenes/v1.0-trainval