version: '3'

services:
  surround_occ:
    image: surround_occ
    tty: true
    stdin_open: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - type: bind
        source: $NUSCENES_DIR/nuScenes-map-expansion-v1.3
        target: /SurroundOcc/data/nuscenes/map