name: "docker build"
description: "docker build and push Composite Action"
inputs:
  docker_image_name:
    description: 'name of the docker image'
    required: true
  docker_context:
    description: 'path to the docker context'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: ghcr.io/ouxt-polaris/ad_model_zoo/${{ inputs.docker_image_name }}:latest
        no-cache: true
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.docker_context }}
