# Project information
site_name: ros_handson
site_url: https://hakuturu583.github.io/ad_model_zoo
site_author: Masaya Kataoka
site_description: ''
copyright: Copyright &copy; 2023 - Masaya Kataoka
docs_dir: models

# Repository
repo_name: ad_model_zoo
repo_url: https://github.com/hakuturu583/ad_model_zoo
edit_uri: edit/master

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - awesome-pages
  - git-revision-date-localized
  - gitsnippet:
      base_dir: models
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          fontFamily: verdana
          fontSize: 12px
          darkMode: false
          background: "#fff"
          primaryColor: "#DEDFEF"
          #secondaryColor: "#000"
          #mainBkg: "#0000"  # affect node bkg
          nodeBorder: "#000"
          clusterBkg: "#fff"
          clusterBorder: "#000"
          #titleColor: "#808080"
          edgeLabelBackground: "#eee"
        logLevel: 5
        securityLevel: loose
        startOnLoad: true
        arrowMarkerAbsolute: false
        flowchart:
          diagramPadding: 8
          nodeSpacing: 50
          rankSpacing: 50
          useMaxWidth: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OUXT_Polaris
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ouxt.polaris.robotx@gmail.com>

extra_css:
  - https://use.fontawesome.com/releases/v5.15.0/css/all.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - mdx_math
  - plantuml_markdown: { server: http://www.plantuml.com/plantuml }
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - toc: { permalink: "#" }
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: README.md
  - Models:
    - TPVFormer: TPVFormer/README.md