name: "docker_build"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        model: [tpv_former]
        include:
          - docker_context: models/TPVFormer
            model: tpv_former
jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/docker_build
        with:
          docker_image_name: ${{ matrix.model }}
          docker_context: ${{ matrix.docker_context }}
