name: "docker_build"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker_build:
    name: docker build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        model: [tpv_former]
        include:
          - docker_context: models/TPVFormer
            model: tpv_former
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/hakuturu583/ad_model_zoo/${{ matrix.model }}:latest
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.docker_context }}
      # - uses: ./.github/actions/docker_build
      #   with:
      #     docker_image_name: ${{ matrix.model }}
      #     docker_context: ${{ matrix.docker_context }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
